bitwarden/gh-actions

lint-workflow/lint.py

Suppresses the file name unless the linter found something. 
Also added the usage of f-strings instead of string concatenation and ran `black` over it to enforce PEP 8.

Surpress filename in linter output

---

lint-workflow/lint.py

There is an edge case that I found for the runner being set to `${{ matrix.os }}`. This change fixes that edge case.

Handling Runner edge case

---

lint-workflow/lint.py

Adds in logic to the `lint.py` script to check Run commands. If there is only a single run command but is on multiple lines, a message will be appended to `findings` to fix the format of the command.
Example:
```yml
- name: Test
run: |
echo "Hello World!"
``` 
Should be
```yml
- name: Test
run:  echo "Hello World!"
```

Checks Run value, alert user if it needs to be a single line

---

get-release-version/action.yml

This PR adds an action that gets the latest GitHub release version from the specified repository.

Add get-release-version action

---

version-bump/main.py

This PR switches the `Sdk` value that is looked for in .NET project files from `Microsoft.NET.Sdk.Web` to `Microsoft.NET.Sdk`.  This handles `csproj` files that don't use the `Web` part of the SDK.  This has been tested with projects that use the`Web` SDK and it still works.

Fix Version Bump Action

---

get-release-version/action.yml

I didn't realize that `shell` is a required property for each step.  Added in the one that was missing.

Add missing property 'shell' to action.yml

---

version-bump/main.py

This PR fixes a formatting issues that were present after running the action.
- Android manifest files should keep formatting and update just the version number.
- JSON files should keep the blank line at the EOF after formatting.

Update Version Bump action to address formatting issues

---

update-rebrandly-link/README.md
update-rebrandly-link/action.yml

This PR adds the `update-rebrandly-link` action for use in our new `self-host` repository workflows.

Add Rebrandly action

---

lint-workflow/lint.py

Adds a way for the linter to check if there is a version update to any public AND Bitwarden Github actions. When there is an update available, it will append a message to the linter output with a link to the newest version. This will allow the engineer to review the update before decided to use it.
Example:

BEEEP: Add GHA version checker to linter

---

version-bump/Dockerfile
version-bump/README.md
version-bump/main.py

This PR introduces functionality to the `version-bump` action so that it can bump Helm charts `Chart.yaml` files.

Update Version Bump action for Helm charts

---

lint-workflow/lint.py

* Add headers to urllib requests so that linting in Github actions works.
* Adds a quick return for local actions to bypass any update check.

Add headers to fix GHA workflows

---

release-version-check/action.yml

Update version convention in dotnet projects to `YYYY.M.R` (no leading zero in the month portion).

Removing leading zero constraint on the dotnet version check

---

.gitignore
lint-workflow/action.yml
lint-workflow/lint.py
lint-workflow/tests/test-alt.yml
lint-workflow/tests/test_a.yaml
lint-workflow/tests/test_action_update.py
lint-workflow/tests/test_lint.py
lint-workflow/tests/test_main.py
lint-workflow/tests/test_workflow_files.py

Improve performance and reduce API overages by only linting workflows that have been changed. 
Test run here: https://github.com/bitwarden/gh-actions/runs/6730350212?check_suite_focus=true
`.gitignore`: 
- Added pytest folders
`lint-workflow/action.yml`: 
- Added an input for workflows(s) to be linted
- Updated yamllint to support multiple files
`lint-workflow/lint.py`:
- Adds an `input_args` parameter to the `main()` function. Allowing the function to be tested easier
- Added workflow_files() function and moves much of the `os` methods into it
- workflow_files() checks the input and finds workflows in any directories
- Spelling changes
- Added `401` check for get_github_api_response()
- Updated formatting
- Adds a `break` for workflows that use local actions
- Restructures logic at end …

Add functionality for passing multiple files into linter

---

.github/workflows/workflow-linter.yml

Reverts bitwarden/gh-actions#59. There is a bug where commits don't get pulled on the first change to a workflow, so it fails the first time using `call-workflow`.

Revert "BEEEP - Update lint-workflow action"

---

download-artifacts/main.js

Fix the issue: https://bitwarden.atlassian.net/browse/DEVOPS-918
Github API returns 100 latest workflows runs from the repo. When the artifact that we are looking for is older than that 100 runs 'cap', we need to look for further pages for it.

Fix download old-ish artifacts

---

version-bump/main.py

This PR updates the output method for the `Version Bump` action to no longer use `set-output` which has been deprecated by GitHub.

Update output method for Version Bump action

---

setup-docker-trust/action.yml

This PR updates the action hashes in the `setup-docker-trust` action to resolve `set-output` warnings.

Update setup-docker-trust action

---

.github/workflows/workflow-linter.yml
lint-workflow/lint.py

Fix workflow linter to  be able to check `bitwarden/sm-action` as normal public gh action and not fail on it. 
-   🐛 Bug fix
-   **lint-workflow/lint.py:** Add check for `bitwarden/gh-actions` instead of `bitwarden` to treat `bitwarden/sm-actrion` as any other public action.
-   ❓ …

Fix workflow linter for bitwarden sm action

---

lint-workflow/.yamllint.yml

All of the actions in our workflows that are updated by Renovate use a single space before comments.  The workflow linter rule has been updated to reflect that.
Update the workflow linter to stop producing warnings on single spaces before comments.
-   **lint-workflow/.yamllint.yml:** Update the `min-spaces-from-content` setting under the `comments` rule.
-   👍 (`:+1:`) or similar for great …

Change linter comment rule for Renovate

---

.github/workflows/test-report-deployment-status-to-slack.yml
report-deployment-status-to-slack/action.yml

https://bitwarden.atlassian.net/browse/DEVOPS-1578
Add github action that can be used across our repos to report deployment status to Slack.
-   **.github/workflows/test-report-deployment-status-to-slack.yml:** Workflow to test the action
- **report-deployment-status-to-slack/action.yml** Composite action that's sending Slack message about deployment status.
-   👍 …

[DEVOPS-1578] Automate QA deploy messages

---

.github/workflows/test-download-artifacts.yml
.github/workflows/test-release-version-check.yml
.github/workflows/workflow-linter.yml
get-keyvault-secrets/README.md
setup-docker-trust/action.yml

```
```
This PR updates all of our action versions to reference `main` instead of `master`.
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

All workflows - Update 'master' to 'main' for any actions in the gh-actions repository

---

download-artifacts/main.js

This PR updates the `download-artifacts` action to fix the issue of not downloading multiple artifacts when listed in the input.
-   **download-artifacts/main.js:** Adds in logic to filter the list of artifacts from the workflow run based on the `artifacts` input.
-   ❓ …

Fix for download-artifacts action

---

report-deployment-status-to-slack/action.yml

https://bitwarden.atlassian.net/browse/DEVOPS-1702
-   🐛 Bug fix
When a workflow is manually cancelled, the slack message is stuck in a constant “deploying” state. As a engineer, I would like the deploy notification of an environment to update to a cancelled emoji when the workflow is cancelled
-   **report-deployment-status-to-slack/action.yml:** Add `cancelled` case in switch with an appropriate message.
-   Updated any necessary documentation or informed the documentation …

[DEVOPS-1702] Add workflow cancellation detection to report-deployment-status-to-slack

---

.github/workflows/test-report-deployment-status-to-slack.yml
report-deployment-status-to-slack/action.yml

- [Card](https://bitwarden.atlassian.net/browse/DEVOPS-1714)
- This PR adds the Commit SHA of the branch or tag deployed to QA to the Slack notification.
-   **report-deployment-status-to-slack/action.yml:** Add the commit sha input, and the input to the slack messages.
-   ❓ …

[DEVOPS- 1714] - Add the Commit SHA of the Branch or Tag Deployed to Slack Messages

---

.github/workflows/workflow-linter.yml

This broke the workflow linter on pull requests.
https://github.com/bitwarden/mobile/actions/runs/7559898444/job/20584746078
Reverts bitwarden/gh-actions#238

Revert "use dynamic repository"

---

.github/workflows/workflow-linter.yml

Reverts bitwarden/gh-actions#237

Revert "[DEVOPS-1597] - Use Action to Get Changed Files"

---

lint-workflow/lint.py

Closes #252
-   🎂 Other
Explained in the linked issue as the first proposed suggestion.
Made the linter rule into a warning.
N/A
- …

Relax the "Run in step ... should be a single line" linter rule

---

report-deployment-status-to-slack/action.yml

- Refactor
- **report-deployment-status-to-slack/action.yml:** Update where input is being passed
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …

[DEVOPS-1752] - Pass Inputs in the Function

---

version-bump/action.yml

-   🐛 Bug fix
This PR removes the default value for the input `version`.  This was causing the version to always be bumped to `2023.12.1` when not specifying a version.
-   **version-bump/action.yml:** Remove `default` key from input `version`. …

DEVOPS-1840 - Remove default input for version

---

download-artifacts/action.yml
download-artifacts/main.js

With our deployments today, we simply output the commit that is in the branch used as the source of the workflow trigger. This doesn't allow us to accurately show which commit is actually deployed, especially in monorepos. This extends this artifact action to set an additional output, `artifact-build-commit:` which allows other actions to use the _real_ commit or "build commit" of the artifact. 
-   **download-artifacts/main.js:** Set the new output to the value of `artifacts`.
- …

[DEVOPS-1919] - Set output for artifact build commit

---

.github/workflows/_enforce-labels.yml
.github/workflows/_version.yml

https://bitwarden.atlassian.net/browse/BRE-30
Create a reusable workflow to compute next version number based on label on PR: `version:major`, `version:minor`, `version:patch`, `version:skip`. Create a pr labels workflow that checks if a version label is not provided on the PR, the PR is blocked from being merged.
-   **.github/workflows/_version.yml:** Add reusable workflow to compute next version from PR label.
- **.github/workflows/_enforce-labels.yml** Add reusable workflow for blocking a PR merge if required labels are absent or if labels that block merge are present.
-   Written new unit and / or integration tests where …

[BRE-30] PR Version labels

---

get-keyvault-secrets/lib/KeyVaultClient.js
get-keyvault-secrets/lib/KeyVaultHelper.js

[BRE-342](https://bitwarden.atlassian.net/browse/BRE-342)
Fix `get-keyvault-secrets` action intermittent failures by implementing retry mechanism with error handling to get secrets from Azure Key Vault. 
Known issues: https://github.com/bitwarden/server/actions/runs/11033476838/job/30644953330
In [this execution](https://github.com/bitwarden/server/actions/runs/11167288532/job/31043397174) we can clearly see that the retry mechanism was executed due to the execution time, `9 seconds` compare to the `6 seconds` when the step failed (RETRY_DELAY = 3000):
https://github.com/bitwarden/server/actions/runs/11167289676/job/31043388477
Multiple jobs were triggered:
-   Written new unit and / or …

BRE-342 Implement retry mechanism with error handling to get secrets from KV

---

.github/workflows/workflow-linter.yml

Internal change
Trigger the Lint workflow job on merge group events. This ensures the required build checks are triggered when a pull request is put into the merge queue.
-   🤔 …

Trigger Lint workflow on merge group events

---

.github/workflows/_version.yml
.github/workflows/lint-ci.yml
.github/workflows/test-download-artifacts.yml
.github/workflows/test-lint-workflow.yml
.github/workflows/test-release-version-check.yml
.github/workflows/test-report-deployment-status-to-slack.yml
.github/workflows/test-report-upcoming-release-version.yml
.github/workflows/test-version-bump.yml
.github/workflows/upload-test-artifacts.yml
.github/workflows/workflow-linter.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-372)
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …

[BRE-372] - Clean up document start

---

lint-workflow/.yamllint.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-370?atlOrigin=eyJpIjoiMGVlY2JlY2I4MmNiNGI4ZmFlNGMzMWU3MzNjMjRmYzMiLCJwIjoiaiJ9)
This PR adds rule settings for `document-start` and `document-end` markers for yamllint.  If a `document-start` or `document-end` marker is in the workflow file, the workflow linter will fail with an error.
-   Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …

BRE-370 - Add rule settings for document-start and document-end markers

---

.prettierignore
download-artifacts/node_modules/before-after-hook/package.json

https://github.com/bitwarden/gh-actions/issues/345
There's a reference to Renovate in a dependency, so just to avoid the linked issue we can remove it. Also tells Prettier to not look at these files.
-   ❓ …

Delete Renovate reference in dependency

---

.github/renovate.json
version-bump/tests/fixtures/test.csproj

Internal change that I just happened to notice.
Still playing around with the dependency management and thought I would perform some manual updates. Also found one more path to ignore, but I am not sure this is working as expected so it may need a follow-up.
-   📝 (`:memo:`) or ℹ️ …

Ignore and update some more references

---

.github/workflows/test-lint-workflow.yml

https://bitwarden.atlassian.net/jira/software/projects/BRE/boards/144?assignee=712020%3Aac9853d4-55a2-4808-acad-e7b7914eac07&selectedIssue=BRE-425
Removing references to ubuntu-latest ahead of an automatic update laster this week 
-   📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or …

[BRE-425] replacing ubuntu-latest with ubuntu-24.04

---

.github/workflows/_ephemeral_environment_manager.yml

This intends to take the existing workflow here https://github.com/bitwarden/devops/blob/main/.github/workflows/_ephemeral_environment_pr_manager.yml and bring it into a public repository. So that we can leverage it in CI workflows directly. Instead of calling `await github.rest.actions.createWorkflowDispatch`. This allows the status of the called workflow to be present directly in the user's CI status.
This also adds additional `sync_environment ` feature that were in the PR here. https://github.com/bitwarden/devops/pull/2957. This adds an input that, when called, syncs the environment based on the pull request.
-   Protected …

BRE-292: Add workflow for ephemeral environment management

---

.github/workflows/_ephemeral_environment_manager.yml

Remove the unused value that is in the title of the step.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could …

BHRE-292: Update step name to not use dynamic value

---

.github/workflows/workflow-linter.yml

Currently the workflow linter is not running, and just succeeding on all PRs.
- [Example 1](https://github.com/bitwarden/clients/actions/runs/13289320851/job/37105759380?pr=13373)
- [Example 2](https://github.com/bitwarden/clients/actions/runs/13288016754/job/37101366071?pr=13374)
- [Example 3](https://github.com/bitwarden/clients/actions/runs/13287740503/job/37100438390?pr=13375)
This PR fixes the workflow linter so that the `changed-workflows` step functions correctly. It further fixes the `if` keys on all the remaining steps, since the output [all_change_files_count](https://github.com/tj-actions/changed-files?tab=readme-ov-file#output_all_changed_files_count) of the `tj-actions/changes-files` action is a string.
-   All formatters and local linters …

Fix Workflow Linter

---

.github/workflows/workflow-linter.yml

This PR removes the validate examples step from the workflow linter since that directory does not exist when this workflow is called from all other repositories and is causing runs to fail. …

Remove validate examples step from Workflow Linter

---

.github/workflows/_ephemeral_environment_manager.yml

Improves how Argo CD CLI will handle when a sync operation is already running for ephemeral environments. This will check if an operation is already running and if so, cancel the sync operation so that a new operation (with the updated tags) will always run.
This resolves the error here: https://github.com/bitwarden/server/actions/runs/13948105343/job/39040836814?pr=5526#step:6:14
-   Updated any necessary documentation (Confluence, …

BRE-724: Improve the robustness of argocd CLI sync operations

---

.github/workflows/check-run.yml

https://bitwarden.slack.com/archives/C024Z7LQNLB/p1743540208424449?thread_ts=1743514779.529319&cid=C024Z7LQNLB
Permits GitHub's merge queue bot to bypass check runs, much like our own bot. Even if merge queues are not used by us, this bot will stay and it doesn't hurt for it to be an exclusion. Anything added to a merge queue should already have met prior checks.
-   Updated any necessary documentation (Confluence, contributing docs) or …

Allow GitHub's merge queue bot to bypass check runs

---

.github/workflows/workflow-linter.yml

https://bitwarden.atlassian.net/browse/BRE-753
was discussed as part of the work for tracking and updating the version of actionlint used in bwwl
we wanted to make this workflow read only …

BRE-753/update-workflow-linter-to-readonly-permissions

---

.github/workflows/_publish-mobile-github-release.yml

https://bitwarden.atlassian.net/browse/BRE-769
Add GitHub Actions workflow for publishing mobile releases. Yhis action will be used in iOS and Android repos:
- https://github.com/bitwarden/ios/pull/1593
- https://github.com/bitwarden/android/pull/5219
-   📝 (`:memo:`) or ℹ️ …

[BRE-769] Add GitHub Actions workflow for publishing mobile releases

---

.github/workflows/_sonar.yml
.github/workflows/test-sonar.yml

Re-work of #424 which was super-outdated and had tons of baggage from merging.
* Add inputs to the test-sonar fixture so that we can manually trigger it and pass the sonar scan type or any inclusions/exclusions if needed
* Make the pull-request number consistent across each type of sonar runner in the reusable workflow
-   👍 (`:+1:`) …

Add test inputs to Sonar tests
