lint-workflow/lint.py

Adds code to check if runner is using `latest` or a pinned version.

Add runner rule

---

install-ast/README.md
install-ast/action.yml

Creating an action to install the version of AST that we use on our projects that sign Windows exe files.

Add AST installation action

---

setup-docker-trust/action.yml

There are a few places where Docker Content Trust is setup. I think it would fit well as a custom action.

Add Setup DCT Action

---

.gitignore
version-bump/README.md
version-bump/main.py
version-bump/tests/test.csproj

Adds support to bump version in projects with .csproj files.
Example:
* https://github.com/bitwarden/key-connector/blob/master/src/KeyConnector/KeyConnector.csproj
* https://github.com/bitwarden/misc/blob/master/AzureFunctions/prod/AppFunctions/AppFunctions.csproj

Version bump/add csproj support

---

.github/workflows/lint-ci.yml
lint-workflow/lint.py
lint-workflow/tests/test.yml
lint-workflow/tests/test_action_update.py
lint-workflow/tests/test_lint.py

Fixes the URL issue by checking if commit sha was for a tag or a commit, if it's a tag, there is an additional api call that needs to be made to pull the commit sha for the tag.
I added in some tests with pytest including a CI workflow.

Fixes issue 25, adds tests as well

---

.github/workflows/workflow-linter.yml

Adds a linting workflow that we can call from other Github projects.

Create main linting workflow

---

update-rebrandly-link/action.yml

This PR fixes a couple of issues I found while using the `update-rebrandly-link` action for the first time.

Update the 'update-rebrandly-link' action

---

crowdin/Dockerfile
crowdin/LICENSE
crowdin/README.md
crowdin/action.yml
crowdin/entrypoint.sh

Add monorepo support to the Crowdin action for our new monorepo repository.
Changes from the original action are lines 214-220.

Custom Monorepo Crowdin Action

---

version-bump/main.py

This PR updates the `Version Bump` action to properly find and update the `Version` XML element.

Update Version Bump action

---

get-release-version/action.yml

Adds monorepo support for this action.
- Adds description
- Adds inputs for monorepo support
- Adds a trim input, to remove letters from the output value if desired.

Support monorepo releases

---

.github/workflows/workflow-linter.yml

Updates the workflow linter to include the changes from https://github.com/bitwarden/gh-actions/pull/54 and https://github.com/bitwarden/gh-actions/pull/49

Bump workflow linter

---

get-checksum/Dockerfile
get-checksum/action.yml
get-checksum/main.py

Add githuib action that will calculate SHA 256 checksums for all files in given folder and save it to the output file.
Related PRs:
- https://github.com/bitwarden/clients/pull/4254
- https://github.com/bitwarden/mobile/pull/2253

Add get checksum action

---

.github/workflows/workflow-linter.yml

Update the logic that builds the list of modified workflows to exclude any workflows that the PR is removing.

Add logic to handle when a workflow gets deleted

---

.github/workflows/workflow-linter.yml

- convert the script to wf inline comment

[DEVOPS-1323] change the script to inline

---

crowdin/action.yml

Found warnings in the [Crowdin Sync](https://github.com/bitwarden/clients/actions/runs/5417833235) workflow.
-   🐛 Bug fix
Fix a missing input for the `crowdin` action.
-   **crowdin/action.yml:** Add `gpg_passphrase` as an input to the action. …

Add missing input to Crowdin action

---

.github/workflows/workflow-linter.yml

Update hash for the workkflow-linter to use newest changes from master.
-   **file.ext:** Description of what was changed and why.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …

Update workflow-linter hash

---

.github/workflows/test-download-artifacts.yml
get-checksum/main.py

-   🐛 Bug fix
-   🎂 Other
- Deprecate GitHub's `set-output` in our workflow.
- **.github/workflows/test-download-artifacts.yml:** to deprecate set-output
- **get-checksum/main.py:** to deprecate set-output
-   📝 (`:memo:`) or ℹ️ …

deprecate set-output

---

setup-docker-trust/action.yml

Related PR: https://github.com/bitwarden/self-host/pull/146
-   **setup-docker-trust/actions.yaml** Fix the deprecated `set-output` command  …

DEVOPS-1408 Refactor setup-docker-trust actions to Retrieve secrets setep to use fixed version bitwarden/gh-actions/get-keyvault-secrets

---

.github/workflows/workflow-linter.yml

Update lint hash.
-   **file.ext:** Description of what was changed and why.
-   🎨 (`:art:`) …

[DEVOPS-1404] Update gh-actions repository workflows

---

.github/workflows/workflow-linter.yml
setup-docker-trust/action.yml

- [Pin all uses of bitwarden/gh-actions to master](https://bitwarden.atlassian.net/browse/DEVOPS-1594)
- For Workflow linting, exempt bitwarden/gh-action hashes check
- **lint-workflow/lint.py:** Make linter skip bitwarden/gh-action hashes check …

make action self-reference master

---

report-deployment-status-to-slack/action.yml

-   🐛 Bug fix
Fix project name in report-deployment-status-to-slack action from strongly typed `Server` to input.
-   **report-deployment-status-to-slack/action.yml:** Change static `Server` to project input. …

Fix project name in report-deployment-status-to-slack action

---

get-keyvault-secrets/README.md
report-deployment-status-to-slack/action.yml

```
```
This PR updates the report-deployment-status-to-slack action versions to reference `main` instead of `master`.
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/)

DEVOPS-1612 Update get-keyvault-secrets action to use 'main' branch

---

LICENSE.txt
LICENSE_BITWARDEN.txt
lint-workflow/tests/fixtures/test_a.yaml

-   🎂 Other
This PR updates some links in our licenses from `master` to `main.
-   **LICENSE.txt:** Update links to look at `main` branch.
- **LICENSE_BITWARDEN.txt:** Update links to look at `main` branch.
- **lint-workflow/tests/fixtures/test_a.yaml:** Update branch for action to `main`. …

Change some references from master to main

---

report-deployment-status-to-slack/action.yml

This PR updates our `Report Deployment Status to Slack` action so that we can update the text of the messages we send.
-   **report-deployment-status-to-slack/action.yml:** Adds the `update-ts` input so that you can specify the ID of the Slack message you'd like to update.  If this input is blank a new message is sent instead. Adds two outputs, `channel_id`, which must be used if you'd like to edit a message as it's the actual channel ID instead of the friendly name of the channel, and `ts`, which is the ID of the Slack message sent, so you can pass that in the next time to edit the message. I also consolidated the Slack actions into one by generating and storing the message in a single step before.
-   All …

Update Report Deployment Status to Slack action to allow editing messages

---

.github/workflows/workflow-linter.yml

- Test Supported Actions Check (to be removed after test)
- Add Workflow dispatch to Linter workflow for testing purposes
-   **file.ext:** Description of what was changed and why.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …

[DEVOPS-1596] - Test Supported Actions Check

---

.github/workflows/workflow-linter.yml

- Edit linter workflow to run in any repo, by any trigger.
- **.github/workflows/workflow-linter.ym:l** Add caveat for linter run
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for …

Devops 1597 edit linter workflow to run anywhere

---

.github/workflows/workflow-linter.yml

- Correct the bug in detecting changed workflow files
-   **.github/workflows/workflow-linter.yml:** Use count to check if workflow files changed …

UPDATE: Use Count to Check Workflow Files Change

---

.github/workflows/workflow-linter.yml

- Using bash script to get changed files is inconsistent when the workflow is called from other repo. We need that step to be consistent because we are now requiring the linter workflow to run from an organizational level. This means it will trigger on every PR even if no file is changed from `.github/workflows/**` path.
-   **.github/workflows/workflow-linter.yml:** Remove the Bash script test for an action …

[DEVOPS-1597] - Use Action to Get Changed Files

---

.github/workflows/workflow-linter.yml

- Checkout dynamically
-   **.github/workflows/workflow-linter.yml:** Checkout dynamically …

use dynamic repository

---

.github/workflows/workflow-linter.yml

- Checkout dynamically
-   **.github/workflows/workflow-linter.yml:** Testing dynamic checkout …

Testing Dynamic Repository Based on Calling Workflow

---

.github/workflows/test-report-deployment-status-to-slack.yml
report-deployment-status-to-slack/action.yml

- [Card](https://bitwarden.atlassian.net/browse/DEVOPS-1733)
-   **.github/workflows/test-report-deployment-status-to-slack.yml:** Test a test-case for Slack report
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …

[ DEVOPS-1733] - Slack Report Test Case Test

---

.github/workflows/test-lint-workflow.yml
lint-workflow/lint.py

- [Card](https://bitwarden.atlassian.net/browse/DEVOPS-1823)
- Update run step to only fail when the block indicator is a pipe and is one line
-   **lint-workflow/lint.py:** Update run step to only fail when the block indicator is a pipe and is one line …

[DEVOPS - 1823] - Edit run Step with Pipe

---

version-bump/main.py

-   🐛 Bug fix
This PR removes the extra text from the `version` output.  When it is used in other workflows we need just the version number.
-   **version-bump/main.py:** Remove `New Version: ` from the `version` output so that it is just the version number.
-   🤔 (`:thinking:`) …

DEVOPS-1840 - Remove extra text from version output

---

.github/workflows/check-run.yml

Internal change.
Lifts the check run workflow out of the template.
-   🎨 (`:art:`) for suggestions / improvements
-   ❌ (`:x:`) or …

Move PR run check from template

---

version-check/action.yml

- [Card](https://bitwarden.atlassian.net/browse/DEVOPS-1840?atlOrigin=eyJpIjoiOWUzNTU3ZDMwODc1NGU2ZDkxMDJlMmQ2MzhiNzljZGEiLCJwIjoiaiJ9)
This PR adds a `version-check` action that will verify that the string passed to it is in the format of `YYYY.MM.P` where `Y` is the four digit year (specifically `20XX`), `M` is the month (`1-12`), and `P` is the patch number.
-   **version-check/action.yml:** Added the `version-check` action.
- …

DEVOPS-1840 - Add version-check action

---

report-deployment-status-to-slack/action.yml

-   🎂 Other
Changes the messaging shown in alerts from "updating" or "updated" to "deploying" or "deployed" to fit the name of the action itself (`deployment-status`). This also should make the messages be more acceptable in the release channels to use this for production environments.
-   **report-deployment-status-to-slack/action.yml:** Change the use of language from "update" to "deploy"
-   👍 (`:+1:`) or similar for great …

Change "Updated" to "Deploy"

---

.github/workflows/enforce-labels.yml

Internal change.
Adds the common label enforcement workflow to the repo so it can be a ruleset used everywhere.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …

Enforce labels workflow

---

.github/workflows/enforce-labels.yml

- Revert The Enforce Label Logic
-   **.github/workflows/enforce-labels.yml:** Revert The Enforce Label Logic
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit …

Revert The Enforce Label Logic

---

.github/workflows/test-report-deployment-status-to-slack.yml

Include `no-changes` event in test coverage
-   **.github/workflows/test-report-deployment-status-to-slack.yml:** Add `no-changes` status
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …

DEVOPS-1782 Include no-changes status in test-report-deployment-status-to-slack.yml

---

get-checksum/main.py

- [Card](https://bitwarden.atlassian.net/browse/BRE-65?atlOrigin=eyJpIjoiMjA2MGYwMTUwMDU3NDg4YmIzN2ViMTc2MDJiMjk1NmUiLCJwIjoiaiJ9)
-   🐛 Bug fix
Fixes https://github.com/bitwarden/clients/issues/9139
This PR fixes the `get-checksum` action by formatting the lines in the resulting checksum file correctly.
-   **get-checksum/main.py:** Changed the spacing between the checksum and filenames and removed the extra space at the end of the lines.
-   Updated any necessary documentation or informed the …

BRE-65 - Fix formatting of lines in checksum file

---

report-deployment-status-to-slack/action.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-77?atlOrigin=eyJpIjoiNmUyODZiYjNlYTY4NDIzZWFlMmNmMzIzYWUwMGM3NTgiLCJwIjoiaiJ9)
-   🐛 Bug fix
This PR updates the `report-deployment-status-to-slack` action to use the `@bre` team tag instead of the old `@devops` team tag for Slack.
-   **report-deployment-status-to-slack/action.yml:** Update tag from `@devops` to `@bre`.
-   📝 …

BRE-77 - Update team from @devops to @bre

---

.github/workflows/test-report-upcoming-release-version.yml
report-upcoming-release-version/action.yml

Jira: https://bitwarden.atlassian.net/browse/BRE-40 
Notify #release with version for upcoming release
To help enable better communication and visibility, and to align the entire company expectations, we would like to send a slack notification to #release with the projects and their corresponding version bumps.
-   Add **report-upcoming-release-version/action.yml:** Initial GitHub Action based on the [report-deployment-status-to-slack action](https://github.com/bitwarden/gh-actions/blob/main/report-deployment-status-to-slack/action.yml)
https://bitwarden.slack.com/archives/C05T0840415/p1715884688154529
- …

BRE-40 Add action for reporting upcoming release version to Slack

---

.github/workflows/test-report-deployment-status-to-slack.yml
report-deployment-status-to-slack/action.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-50)
-   🤖 Build/deploy pipeline (BRE)
-   **.github/workflows/test-report-deployment-status-to-slack.yml:** Update test workflow to match Slack report update
- **report-deployment-status-to-slack/action.yml:** Upgrade slack messages to a new pattern
-   ❓ …

[BRE-50] Upgrade Slack Messages To New Pattern

---

.github/workflows/test-report-deployment-status-to-slack.yml
.github/workflows/test-report-upcoming-release-version.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-83)
-   ***:** Rename references to old slack notifications test channel
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …

[BRE-83] - Rename Channel

---

lint-workflow-v2/pyproject.toml.tpl

-   🐛 Bug fix
-   🎂 Other
Fix the workflow linter build/install via `pip`
-   **pyproject.toml:** remove the string to prevent the build from failing. …

Remove string author to allow for build/install

---

download-artifacts/action.yml

https://bitwarden.atlassian.net/browse/BRE-94
-   🎂 Other
-   **download-artifacts/action.yml:** Set `allow_forks` default to `false` in `bitwarden/gh-actions/download-artifacts`.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed …

[BRE-94] Patch `download-artifacts` action allow_forks input

---

download-artifacts/action.yml
download-artifacts/main.js

- [Card](https://bitwarden.atlassian.net/browse/BRE-49)
-   **download-artifacts/main.js:** Add the logic to output Artifact build branch
-   **download-artifacts/action.yml:** Add output …

[BRE-49] Add Artifact Build Branch

---

.github/workflows/_enforce-labels.yml

-   🎂 Other
Since the `Template CI/CD` epic has been pushed to Q4 we're disabling the check for `version` label to not block PRs without it.
-   **.github/workflows/_enforce-labels.yml:** Comment out `enforce-version-label`. …

Disable `enforce-version-label`

---

.github/renovate.json

Internal change.
Groups dependency updates by folder. We are using this for collector-style repos that maintain each module independently.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …

Group dependency updates by folder

---

.github/workflows/check-run.yml

- remove gh app from users to check in check-run workflow
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could …

[BRE-246] - Remove GH App From Users to Check in check-run Workflow

---

report-deployment-status-to-slack/action.yml

Improve slack failure message
- …

Refactor Slack Failure message

---

.github/workflows/check-run.yml

- [Card](https://bitwarden.atlassian.net/browse/BRE-343)
- Reverts #316 
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …

Revert BRE-343

---

lint-workflow/lint.py

- [Context](https://bitwarden.slack.com/archives/C024Z7LQNLB/p1727879448072759)
This PR allows actions that are stored in any Bitwarden repository to be pinned to non-hash values.
- …

Allow any Bitwarden actions to be pinned to non-hash values

---

.github/workflows/_enforce-labels.yml
.github/workflows/_version.yml
.github/workflows/check-run.yml
.github/workflows/lint-ci.yml
.github/workflows/scan.yml
.github/workflows/test-download-artifacts.yml
.github/workflows/test-report-deployment-status-to-slack.yml
.github/workflows/test-report-upcoming-release-version.yml
.github/workflows/upload-test-artifacts.yml
.github/workflows/workflow-linter.yml

Reverts bitwarden/gh-actions#328

Revert "[deps]: Update ubuntu to v24"

---

lint-workflow/lint.py

- [Card](https://bitwarden.atlassian.net/browse/BRE-383)
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …

[BRE-383] - fix the bug

---

.github/workflows/test-report-deployment-status-to-slack.yml
report-deployment-status-to-slack/action.yml

[BRE-265](https://bitwarden.atlassian.net/browse/BRE-265)
Updates slack notifications to use links for tag/branch and commit information. …

BRE-265-slack-commit-link

---

.github/renovate.json

Follow-up to https://github.com/bitwarden/gh-actions/pull/344.
Also ignore dependencies we don't manage in `node_modules`. …

Ignore modules with Renovate too

---

.github/workflows/workflow-linter.yml

- [BRE-706](https://bitwarden.atlassian.net/browse/BRE-706?atlOrigin=eyJpIjoiYjc0ODgwNzcyYTE4NGM5NmJjMjg3MTBjOWUwZTM4MzQiLCJwIjoiaiJ9)
This PR removes the compromised action `tj-actions/changed-files` and allows the linter to lint on changes to any file.
I have another [PR](https://github.com/bitwarden/gh-actions/pull/368) that will need review to add in the replacement logic that the action was used for.
-   Updated any necessary …

BRE-706 - Remove compromised action

---

.github/templates/workflow-templates/example-references/_test.yml

Internal change.
Removes the Codecov token which is no longer needed to upload results. …

Remove references to Codecov token

---

.github/workflows/_ephemeral_environment_manager.yml

Adds a new job that creates a branch with prefixed information for Ephemeral Environments. …

Add create_branch job for Ephemeral Environments

---

.github/workflows/workflow-linter.yml

bump python version to match changes being made as part of https://github.com/bitwarden/workflow-linter/pull/96 
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …

bump bwwl python version

---

.github/workflows/_ephemeral_environment_manager.yml

Fixes a repository name and updates the dependency mapping for the `sync` job to require the branch to be created.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …

Update ephemeral environment workflow with dependency mapping

---

.github/workflows/_ephemeral_environment_manager.yml

Add origin and branch details.
- …

Fix git push by using it properly

---

.github/workflows/_ephemeral_environment_manager.yml

I think making it more descriptive here that this is a `config` branch makes a lot of sense. …

Update _ephemeral_environment_manager.yml to make branch name more descriptive

---

.github/workflows/_ephemeral_environment_manager.yml

We no longer use these inputs since it's performed by default.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could …

Cleanup unused inputs for ephemeral environments

---

.github/workflows/check-run.yml

Reverts bitwarden/gh-actions#373

Revert "Allow GitHub's merge queue bot to bypass check runs"

---

.github/workflows/workflow-linter.yml

BRE-753 was the ticket that produced this change
syntax / formatting error with the permissions block nested inside of `on`
bumped it out to the root level …

correctly format permissions block

---

.github/workflows/workflow-linter.yml

https://bitwarden.atlassian.net/browse/BRE-849
- Update the argument passed into `bwwl` CLI in the worklfow-linter file to take in files instead of directory.
-   🤔 (`:thinking:`) or …

[BRE-849] - Update bwwl File Argument

---

get-keyvault-secrets/lib/KeyVaultHelper.js
get-keyvault-secrets/src/KeyVaultHelper.ts

[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Only setting secrets as output rather than output + env.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …

[BRE-831] Removing exporting secret to env

---

.github/workflows/check-run.yml

https://bitwarden.atlassian.net/browse/VULN-252
Further restrict permissions to check-run, to prevent abuse of github tokens …

Specify permissions for check-run action

---

.github/workflows/_ephemeral_environment_manager.yml

related to https://bitwarden.atlassian.net/browse/VULN-252
Add permissions to allow linting to pass for #406
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …

Added permissions to ephemeral_environment_manager.yml to fix lint

---

.github/workflows/_ephemeral_environment_manager.yml
.github/workflows/scan.yml

https://bitwarden.atlassian.net/browse/VULN-252
Further restrict permissions to check-run, to prevent abuse of github tokens …

Fix permissions for check-run action

---

.github/workflows/test-get-secrets.yml
.github/workflows/test-lint-workflow.yml

[BRE-848](https://bitwarden.atlassian.net/browse/BRE-848)
Adding permissions to fix rate limiting issue
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …

BRE-848 Adding Permissions

---

.github/workflows/_ephemeral_environment_manager.yml
.github/workflows/_publish-mobile-github-release.yml
.github/workflows/scan.yml
.github/workflows/test-get-secrets.yml
.github/workflows/test-report-deployment-status-to-slack.yml
.github/workflows/test-report-upcoming-release-version.yml
report-deployment-status-to-slack/action.yml
report-upcoming-release-version/action.yml
setup-docker-trust/action.yml

[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Support migrating secrets to AKV
File Updates:
1. .github/workflows/_ephemeral_environment_manager.yml
- Only used in server:
- server/.github/workflows/build.yml
- server/.github/workflows/ephemeral-environment.yml
- Marking as *hold* until the server managed identity has access to the bitwardenci KV.
2. .github/workflows/test-report-deployment-status-to-slack.yml
- Tests the update including backward compatibility with the SP creds.
3. .github/workflows/test-report-upcoming-release-version.yml
- Tests the update including backward compatibility with the SP creds.
4. report-deployment-status-to-slack/action.yml
- This is backward compatible and works with a SP creds or the OIDC IDs.  At least one of those is required.
5. …

BRE-831 migrate secrets akv

---

setup-docker-trust/action.yml

[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Fixing setup-docker-trust action …

[BRE-831] Fixing setup-docker-trust action

---

.github/workflows/_checkmarx.yml

Update the Checkmarx scan version to the newest release, to help with troubleshooting issues in other repositories.
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …

Update checkmarx/ast-github-action action version

---

.github/workflows/test-checkmarx.yml
.github/workflows/test-sonar.yml

Adds a test to help support this PR:
https://github.com/bitwarden/gh-actions/pull/422  …

Testing checkmarx/sonar test

---

.github/copilot-instructions.md

[bre-1039](https://bitwarden.atlassian.net/browse/bre-1039)
as part of a PoC for enabling automamtic PR reviews from copilot, we are creating instruction files to tune responses
- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team
- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 …

[bre-1039] add copilot instructions file

---

.github/CODEOWNERS

Change ownership of security-scan related files to the @bitwarden/team-appsec 
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue …

Change ownership of security scan files to AppSec
